import type { Product } from "./types.js";

/** Editable demonstration catalog. Prices are examples, not live store quotations. */
export const products: Product[] = [
  {
    id: "picanha",
    name: "Picanha",
    category: "bovina",
    price: 69.9,
    available: true,
    image: "/fotos/produtos/bovina/picanha.jpg",
    description: "",
    preps: ["Bifes", "Peça inteira"],
    unitWeight: 0.2,
    promotion: {
      label: "Oferta do dia",
      oldPrice: 79.9,
    },
  },
  {
    id: "patinho",
    name: "Patinho",
    category: "bovina",
    price: 39.9,
    available: true,
    image: "/fotos/produtos/bovina/patinho.jpg",
    description: "",
    preps: ["Bifes", "Cubos", "Tiras", "Moído"],
    unitWeight: 0.15,
  },
  {
    id: "contrafile",
    name: "Contrafilé",
    category: "bovina",
    price: 49.9,
    available: true,
    image: "/fotos/produtos/bovina/contrafile.jpg",
    description: "",
    preps: ["Bifes", "Tiras", "Peça inteira"],
    unitWeight: 0.18,
    promotion: {
      label: "Oferta do dia",
      oldPrice: 59.9,
    },
  },
  {
    id: "alcatra",
    name: "Alcatra",
    category: "bovina",
    price: 44.9,
    available: true,
    image: "/fotos/produtos/bovina/alcatra.jpg",
    description: "",
    preps: ["Bifes", "Cubos", "Tiras", "Moído", "Peça inteira"],
    unitWeight: 0.15,
  },
  {
    id: "file-mignon",
    name: "Filé mignon",
    category: "bovina",
    price: 79.9,
    available: true,
    image: "/fotos/produtos/bovina/file-mignon.jpg",
    description: "",
    preps: ["Bifes", "Medalhões", "Cubos", "Tiras", "Peça inteira"],
    unitWeight: 0.15,
  },
  {
    id: "fraldinha",
    name: "Fraldinha",
    category: "bovina",
    price: 42.9,
    available: true,
    image: "/fotos/produtos/bovina/fraldinha.jpg",
    description: "",
    preps: ["Bifes", "Tiras", "Moído", "Peça inteira"],
    unitWeight: 0.15,
  },
  {
    id: "coxao-mole",
    name: "Coxão mole",
    category: "bovina",
    price: 38.9,
    available: true,
    image: "/fotos/produtos/bovina/coxao-mole.jpg",
    description: "",
    preps: ["Bifes", "Cubos", "Tiras", "Moído", "Peça inteira"],
    unitWeight: 0.15,
  },
  {
    id: "coxao-duro",
    name: "Coxão duro",
    category: "bovina",
    price: 34.9,
    available: true,
    image: "/fotos/produtos/bovina/coxao-duro.jpg",
    description: "",
    preps: ["Bifes", "Cubos", "Moído", "Peça inteira"],
    unitWeight: 0.15,
  },
  {
    id: "lagarto",
    name: "Lagarto",
    category: "bovina",
    price: 36.9,
    available: true,
    image: "/fotos/produtos/bovina/lagarto.jpg",
    description: "",
    preps: ["Bifes", "Cubos", "Peça inteira"],
    unitWeight: 0.15,
  },
  {
    id: "musculo",
    name: "Músculo",
    category: "bovina",
    price: 28.9,
    available: true,
    image: "/fotos/produtos/bovina/musculo.jpg",
    description: "",
    preps: ["Cubos", "Pedaços", "Moído", "Peça inteira"],
    unitWeight: 0.15,
  },
  {
    id: "maminha",
    name: "Maminha",
    category: "bovina",
    price: 45.9,
    available: true,
    image: "/fotos/produtos/bovina/maminha.jpg",
    description: "",
    preps: ["Bifes", "Peça inteira"],
    unitWeight: 0.15,
  },
  {
    id: "acem",
    name: "Acém",
    category: "bovina",
    price: 29.9,
    available: true,
    image: "/fotos/produtos/bovina/acem.jpg",
    description: "",
    preps: ["Bifes", "Cubos", "Moído", "Peça inteira"],
    unitWeight: 0.15,
  },
  {
    id: "paleta",
    name: "Paleta",
    category: "bovina",
    price: 31.9,
    available: true,
    image: "/fotos/produtos/bovina/paleta.jpg",
    description: "",
    preps: ["Bifes", "Cubos", "Moído", "Peça inteira"],
    unitWeight: 0.15,
  },
  {
    id: "cupim",
    name: "Cupim",
    category: "bovina",
    price: 39.9,
    available: true,
    image: "/fotos/produtos/bovina/cupim.jpg",
    description: "",
    preps: ["Bifes", "Peça inteira"],
    unitWeight: 0.15,
  },
  {
    id: "costela-bovina",
    name: "Costela bovina",
    category: "bovina",
    price: 26.9,
    available: true,
    image: "/fotos/produtos/bovina/costela.jpg",
    description: "",
    preps: ["Tiras", "Pedaços", "Peça inteira"],
    unitWeight: 0.15,
  },
  {
    id: "rabada",
    name: "Rabada",
    category: "bovina",
    price: 32.9,
    available: true,
    image: "/fotos/produtos/bovina/rabada.jpg",
    description: "",
    preps: ["Pedaços"],
    unitWeight: 0.15,
  },
  {
    id: "peito-frango",
    name: "Peito de frango",
    category: "frango",
    price: 21.9,
    available: true,
    image: "/fotos/produtos/frango/peito-frango.jpg",
    description: "",
    preps: ["Filés", "Cubos", "Tiras", "Moído", "Peça inteira"],
    unitWeight: 0.15,
    promotion: {
      label: "Oferta do dia",
      oldPrice: 25.9,
    },
  },
  {
    id: "coxa",
    name: "Coxa e sobrecoxa",
    category: "frango",
    price: 16.9,
    available: true,
    image: "/fotos/produtos/frango/coxa-sobrecoxa.jpg",
    description: "",
    preps: ["Peça inteira", "Pedaços"],
    unitWeight: 0.25,
  },
  {
    id: "coxa-frango",
    name: "Coxa de frango",
    category: "frango",
    price: 15.9,
    available: true,
    image: "/fotos/produtos/frango/coxa.jpg",
    description: "",
    preps: ["Inteira", "Pedaços"],
    unitWeight: 0.15,
  },
  {
    id: "sobrecoxa-frango",
    name: "Sobrecoxa de frango",
    category: "frango",
    price: 17.9,
    available: true,
    image: "/fotos/produtos/frango/sobrecoxa.jpg",
    description: "",
    preps: ["Inteira", "Desossada", "Pedaços"],
    unitWeight: 0.2,
  },
  {
    id: "asinha-frango",
    name: "Asinha de frango",
    category: "frango",
    price: 18.9,
    available: true,
    image: "/fotos/produtos/frango/asinha.jpg",
    description: "",
    preps: ["Inteira", "Separada em partes"],
    unitWeight: 0.08,
  },
  {
    id: "lombo",
    name: "Lombo suíno",
    category: "suina",
    price: 29.9,
    available: true,
    image: "/fotos/produtos/suina/lombo.jpg",
    description: "",
    preps: ["Bifes", "Cubos", "Peça inteira"],
    unitWeight: 0.15,
    promotion: {
      label: "Oferta do dia",
      oldPrice: 34.9,
    },
  },
  {
    id: "file-mignon-suino",
    name: "Filé mignon suíno",
    category: "suina",
    price: 32.9,
    available: true,
    image: "/fotos/produtos/suina/file-mignon.jpg",
    description: "",
    preps: ["Bifes", "Medalhões", "Cubos", "Tiras", "Peça inteira"],
    unitWeight: 0.15,
  },
  {
    id: "bisteca-suina",
    name: "Bisteca suína",
    category: "suina",
    price: 24.9,
    available: true,
    image: "/fotos/produtos/suina/bisteca.jpg",
    description: "",
    preps: ["Bifes"],
    unitWeight: 0.15,
  },
  {
    id: "pernil-suino",
    name: "Pernil suíno",
    category: "suina",
    price: 23.9,
    available: true,
    image: "/fotos/produtos/suina/pernil.jpg",
    description: "",
    preps: ["Bifes", "Cubos", "Peça inteira"],
    unitWeight: 0.15,
  },
  {
    id: "copa-lombo",
    name: "Copa lombo",
    category: "suina",
    price: 28.9,
    available: true,
    image: "/fotos/produtos/suina/copa-lombo.jpg",
    description: "",
    preps: ["Bifes", "Cubos", "Peça inteira"],
    unitWeight: 0.15,
  },
  {
    id: "panceta",
    name: "Panceta",
    category: "suina",
    price: 29.9,
    available: true,
    image: "/fotos/produtos/suina/panceta.jpg",
    description: "",
    preps: ["Tiras", "Cubos", "Peça inteira"],
    unitWeight: 0.15,
  },
  {
    id: "costela-suina",
    name: "Costela suína",
    category: "suina",
    price: 27.9,
    available: true,
    image: "/fotos/produtos/suina/costela.jpg",
    description: "",
    preps: ["Tiras", "Pedaços", "Peça inteira"],
    unitWeight: 0.15,
  },
  {
    id: "picanha-suina",
    name: "Picanha suína",
    category: "suina",
    price: 34.9,
    available: true,
    image: "/fotos/produtos/suina/picanha.jpg",
    description: "",
    preps: ["Bifes", "Peça inteira"],
    unitWeight: 0.15,
  },
  {
    id: "carre-suino",
    name: "Carré suíno",
    category: "suina",
    price: 36.9,
    available: true,
    image: "/fotos/produtos/suina/carre-suino.jpg",
    description: "",
    preps: ["Peça inteira", "Bifes"],
    unitWeight: 0.15,
  },
  {
    id: "linguica-defumada",
    name: "Linguiça defumada",
    category: "embutidos",
    price: 27.9,
    available: true,
    image: "/fotos/produtos/embutidos/linguica-defumada.jpg",
    description: "",
    preps: ["Inteira", "Rodelas"],
    unitWeight: 0.1,
  },
  {
    id: "linguica-bovina",
    name: "Linguiça bovina",
    category: "embutidos",
    price: 32.9,
    available: true,
    image: "/fotos/produtos/embutidos/linguica-bovina.jpg",
    description: "",
    preps: ["Inteira", "Rodelas"],
    unitWeight: 0.1,
  },
  {
    id: "linguica-frango",
    name: "Linguiça de frango",
    category: "embutidos",
    price: 22.9,
    available: true,
    image: "/fotos/produtos/embutidos/linguica-frango.jpg",
    description: "",
    preps: ["Inteira", "Rodelas"],
    unitWeight: 0.1,
  },
  {
    id: "linguica-suina",
    name: "Linguiça suína",
    category: "embutidos",
    price: 23.9,
    available: true,
    image: "/fotos/produtos/embutidos/linguica-suina.jpg",
    description: "",
    preps: ["Inteira", "Rodelas"],
    unitWeight: 0.1,
  },
  {
    id: "linguica",
    name: "Linguiça toscana",
    category: "embutidos",
    price: 24.9,
    available: true,
    image: "/fotos/produtos/embutidos/linguica-toscana.jpg",
    description: "",
    preps: ["Inteira", "Rodelas"],
    unitWeight: 0.1,
  },
  {
    id: "linguica-paio",
    name: "Linguiça paio",
    category: "embutidos",
    price: 29.9,
    available: true,
    image: "/fotos/produtos/embutidos/linguica-paio-tabua.jpg",
    description: "",
    preps: ["Inteira", "Rodelas"],
    unitWeight: 0.1,
  },
  {
    id: "coracao-galinha",
    name: "Coração de galinha",
    category: "miudos",
    price: 24.9,
    available: true,
    image: "/fotos/produtos/miudos/coracao-galinha.jpg",
    description: "",
    preps: ["Inteiro"],
    unitWeight: 0.15,
  },
  {
    id: "lingua-boi",
    name: "Língua de boi",
    category: "miudos",
    price: 26.9,
    available: true,
    image: "/fotos/produtos/miudos/lingua-boi.jpg",
    description: "",
    preps: ["Inteira", "Fatias"],
    unitWeight: 0.15,
  },
  {
    id: "bucho-boi",
    name: "Bucho de boi",
    category: "miudos",
    price: 18.9,
    available: true,
    image: "/fotos/produtos/miudos/bucho-boi.jpg",
    description: "",
    preps: ["Tiras", "Pedaços"],
    unitWeight: 0.15,
  },
  {
    id: "figado",
    name: "Fígado bovino",
    category: "miudos",
    price: 21.9,
    available: true,
    image: "/fotos/produtos/miudos/figado.jpg",
    description: "",
    preps: ["Bifes", "Iscas"],
    unitWeight: 0.15,
  },
  {
    id: "pe-galinha",
    name: "Pé de galinha",
    category: "miudos",
    price: 8.9,
    available: true,
    image: "/fotos/produtos/miudos/pe-galinha.png",
    description: "",
    preps: ["Inteiro"],
    unitWeight: 0.15,
  },
  {
    id: "moela",
    name: "Moela",
    category: "miudos",
    price: 16.9,
    available: true,
    image: "/fotos/produtos/miudos/moela.jpg",
    description: "",
    preps: ["Inteira", "Pedaços"],
    unitWeight: 0.15,
  },
];
